version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://ronaltest:ronaltest@cluster0.t3n3f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0